language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env: TMPDIR=/tmp

install:
 - sh ./tests/install_dependencies.sh
 - phpenv rehash

services:
  - memcached

before_script:
  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres
  - echo "extension = memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`;
  - echo "extension = memcached.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`;
  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
 - cd tests/
 - php runalltests.php
 
matrix:
  allow_failures:
   - php: hhvm
